version: "2.3"
services:
  vpn:
    image: poyaz/forticlient:latest
    network_mode: bridge
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    volumes:
      - ./storage/docker/2fa:/tmp/2fa
    cap_add:
      - NET_ADMIN
    ports:
      - "127.0.0.1:${FORTI_PROXY_PORT:-1080}:1080"
      - "127.0.0.1:${FORTI_DNS_PORT:-1081}:1081/tcp"
      - "127.0.0.1:${FORTI_DNS_PORT:-1081}:1081/udp"
      - "127.0.0.1:${FORTI_SSH_PORT:-1082}:1082"
    expose:
      - 1080
      - 1081
      - 1082
    restart: "always"
    logging:
      driver: ${VPN_LOG_DRIVER:-json-file}
      options:
        max-size: ${VPN_LOG_MAX_SIZE:-2m}
        max-file: ${VPN_LOG_MAX_FILE:-10}

  socks5:
    image: ghcr.io/sagernet/sing-box
    depends_on:
      vpn:
        condition: service_healthy
    volumes:
      - $PWD/storage/docker/proxy/:/etc/sing-box/
    command:
      - -D
      - /var/lib/sing-box
      - -C
      - /etc/sing-box/
      - run
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    healthcheck:
      test: [ "CMD-SHELL", "test `ip -o a show | cut -d ' ' -f 2 | grep ppp0 | wc -l` -eq 1 || kill 1" ]
      interval: 11s
      timeout: 2s
    restart: "always"
    network_mode: "service:vpn"
    logging:
      driver: ${VPN_LOG_DRIVER:-json-file}
      options:
        max-size: ${VPN_LOG_MAX_SIZE:-2m}
        max-file: ${VPN_LOG_MAX_FILE:-10}
